// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeDrawnCardsButton': string;
  'content': string;
  'drawnCardsSwitchButton': string;
  'drawnCardsSwitchPanel': string;
  'gameplayStatistics': string;
  'negativeStatistic': string;
  'positiveStatistic': string;
  'separator': string;
  'statisticWithIcon': string;
  'victoryIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
