// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boldText': string;
  'howToPlay': string;
}
export const cssExports: CssExports;
export default cssExports;
