// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'interactive': string;
  'listingItem': string;
}
export const cssExports: CssExports;
export default cssExports;
