// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'drawnCardsChoiceLabel': string;
  'newGame': string;
  'title': string;
  'titleImage': string;
}
export const cssExports: CssExports;
export default cssExports;
