// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'confirmButton': string;
  'overlay': string;
  'themePreview': string;
}
export const cssExports: CssExports;
export default cssExports;
