// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'option': string;
  'optionUiContainer': string;
  'selectedOptionOverlay': string;
  'themeChoice': string;
}
export const cssExports: CssExports;
export default cssExports;
