// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomBar': string;
  'button': string;
  'buttonWrapper': string;
  'content': string;
  'contentWrapper': string;
  'icon': string;
}
export const cssExports: CssExports;
export default cssExports;
