// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'body': string;
  'card': string;
  'front': string;
  'isHinted': string;
  'shadow': string;
}
export const cssExports: CssExports;
export default cssExports;
