// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'desk': string;
  'greenS': string;
  'greenSImage': string;
  'greenSImageWrapper': string;
  'greenSInnerImageWrapper': string;
  'stock': string;
  'topBar': string;
}
export const cssExports: CssExports;
export default cssExports;
