// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'draggable': string;
  'isDragged': string;
}
export const cssExports: CssExports;
export default cssExports;
