// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'flipHeaderButtons': string;
  'hasTitle': string;
  'header': string;
  'headerButton': string;
  'headerButtonContainer': string;
  'headerTitle': string;
  'isDrawer': string;
  'isOpen': string;
  'modalContentHost': string;
  'overlay': string;
  'ui': string;
  'uiWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
