// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pile': string;
  'pileCardWrapper': string;
  'pileCards': string;
  'pileDropArea': string;
  'revealedCardHolder': string;
  'tableau': string;
  'tableauContent': string;
  'unrevealedCardHolder': string;
}
export const cssExports: CssExports;
export default cssExports;
