// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pile': string;
  'pileCardHolder': string;
  'pileCardWrapper': string;
  'pileCards': string;
  'tableau': string;
  'tableauContent': string;
}
export const cssExports: CssExports;
export default cssExports;
