// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'divider': string;
  'dynamicInfo': string;
  'icon': string;
  'isPhoneOrTablet': string;
  'settings': string;
  'settingsPane': string;
  'sideContent': string;
  'statsPane': string;
  'textContent': string;
  'title': string;
  'topBar': string;
}
export const cssExports: CssExports;
export default cssExports;
