// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardHolder': string;
  'foundationPile': string;
  'separator': string;
  'stackedCard': string;
  'stock': string;
  'topBar': string;
  'topBarContent': string;
  'topBarItem': string;
  'waste': string;
}
export const cssExports: CssExports;
export default cssExports;
